### ISSUE TITLE
Webstart Exporter: corrections

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#382]
Export checked with Hisbus-Bildungsverläufe (compared with export of @vdick). The data looks good. Two changes would be great: 
- [x] "null"-values (current state) should be -9999
- [x] date format is now "d/mm/yy hh:mm AM" and should be "dd.mm.yyyy hh:mm:ss" instead

**Comment by dzhwmeisner** [comment]
Null Values are now replaced by -9999 (maybe it should be configurable) 
Date Format is as requested with additional seconds.
Request for Testing

**Comment by andreaschu** [comment]
Testet on Lehrbuchstudie Bibliotheken.
The date format seems to be fine.
The missing code -9999 seems to be completely deleted. Instead the field is empty.

**Comment by dzhwmeisner** [comment]
fixed and deployed. Request for testing.

**Comment by andreaschu** [comment]
I didn't found any 'null'-values. But there are now a lot of missings without any definition (empty fields like "").
Date format is fine.
(Testet with Lehrbuch_Bibliotheken.)

**Comment by andreaschu** [comment]
There are still the same amount of empty fields ("") and addionally to that, there are the "new" Missing code "DEFAULT".
I also found the code "NOPAGE".
All has to be coded with our categories.

**Comment by andreaschu** [comment]
NOPAGE should be -9995
research showed, NULLVALUE should be -9992
