### ISSUE TITLE
calendar: events are not editable on mobile devices if on the right side

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#439]
events can not be choosen to edit when the data is entered once (e.g., when you select a month on the right side, the modal pops up way to far right to be, such that some buttons are hidden) (see first screenshot)

![grafik](https://user-images.githubusercontent.com/30111489/130740043-88dce3d1-cd37-4a1d-a078-5ae17a9589bf.png)

**Comment by andreaschu** [comment]
centre the dialog window

**Comment by dzhwmeisner** [comment]
fixed in new Rollout by adding css to style and position dialog

**Comment by dzhwmeisner** [comment]
request for testing

**Comment by andreaschu** [comment]
I still cannot open the dialog if the event I am going to edit is in April, August or December, because the edit or delete dialog is too far on the right side. 
To me nothing has been changed on this issue, or did I got it wrong?
(tested on firefox simulation for iPhone 12/13+pro iOS 14.6).

![grafik](https://user-images.githubusercontent.com/30111489/151011833-1562c5aa-68a6-47b9-9bc9-58dd3751aa01.png)

**Comment by dzhwmeisner** [comment]
orientation of menu items changed on right side and menu positioned. Please test again

**Comment by andreaschu** [comment]
It works now! Thanks.
Please put it on the left for the months March, July and November, since these are not editable on some devices/ screen sizes.

**Comment by dzhwmeisner** [comment]
left alignment extended for March, July and November

**Comment by andreaschu** [comment]
Great! I can close this issue then. 😃
